spring:
  datasource:
    url: jdbc:mysql://localhost:3304/order_db
    username: jeffpine
    password: 843657jf
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # Para debug
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 30 # Melhora performance para inserts em massa
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
    server:
      error:
        include-message: always
        include-binding-errors: always